# Base configs
# baseurl: "http://00bcat.github.io/photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by Jenny"
subtitle: "See the world through my eyes!"
author: "Jenny"
bio: "I am super beautiful."
publicise: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork it on github</a> ;)"
web_design: "AJ"
social_urls:
  facebook: ""
  twitter: ""
  instagram: ""
  dribbble: ""
  linkedin: ""
  github: "https://www.github.com/00bcat"
  